name: Build and Test

on: 
  workflow_dispatch:
  push:
    branches: 
      - 'main'
  pull_request:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_id || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace }}/nuget
  NuGetSource: https://nuget.pkg.github.com/Vulthil/index.json

jobs:
  create_nuget:
    runs-on: ubuntu-latest
    outputs:
      stable_version: ${{ steps.extract_version.outputs.stable_version }}
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
        filter: tree:0
    - uses: actions/setup-dotnet@v5
    - name: Restore .NET tools
      run: dotnet tool restore
    - name: Extract Version
      id: extract_version
      run: |
        VERSION=$(dotnet minver)
        if [ "${GITHUB_REF}" == "refs/heads/main" ]; then
          STABLE_VERSION=$(echo $VERSION | cut -d "-" -f 1)
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git tag $STABLE_VERSION
          git push origin $STABLE_VERSION
        else
          STABLE_VERSION=$VERSION
        fi
        echo "STABLE_VERSION=$STABLE_VERSION" >> $GITHUB_ENV
        echo "stable_version=$STABLE_VERSION" >> $GITHUB_OUTPUT
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Pack
      run: dotnet pack --configuration Release --output ${{ env.NuGetDirectory }} -p:PackageVersion=${{ steps.extract_version.outputs.STABLE_VERSION }}
    - uses: actions/upload-artifact@v5
      with:
        name: nuget
        if-no-files-found: error
        retention-days: 7
        path: ${{ env.NuGetDirectory }}/*.nupkg

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-dotnet@v5
    - name: Test
      run: dotnet test --configuration Release
   
  deploy_preview:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: [ create_nuget, test ]
    steps:
    - uses: actions/download-artifact@v6
      with:
        name: nuget
        path: ${{ env.NuGetDirectory }}
    - name: Publish Preview NuGet package
      run: |
        for file in "${{ env.NuGetDirectory }}"/*.nupkg ; do
            dotnet nuget push "$file" --api-key "${{ secrets.GITHUB_TOKEN }}" --source "${{ env.NuGetSource }}" --skip-duplicate --symbol-source "${{ env.NuGetSource }}" --symbol-api-key "${{ secrets.GITHUB_TOKEN }}"
        done
  
  create_release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [ create_nuget, test ]
    env:
      STABLE_VERSION: ${{ needs.create_nuget.outputs.stable_version }}
    steps:
    - uses: actions/checkout@v5
    - name: Create GitHub Release
      uses: elgohr/Github-Release-Action@v5
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: ${{ env.STABLE_VERSION }}
        title: Release v${{ env.STABLE_VERSION }}
        prerelease: false

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [ create_nuget, test, create_release ]
    steps:
    - uses: actions/download-artifact@v6
      with:
        name: nuget
        path: ${{ env.NuGetDirectory }}
    - name: Publish NuGet package
      run: |
        for file in "${{ env.NuGetDirectory }}"/*.nupkg ; do
            dotnet nuget push "$file" --api-key "${{ secrets.GITHUB_TOKEN }}" --source "${{ env.NuGetSource }}" --skip-duplicate
        done
  