name: Build and Test

on: 
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

jobs:
  analyze:
    runs-on: ubuntu-latest
    outputs:
      has_changes: ${{ steps.check.outputs.has_changes }}
      
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      
      - name: Install dotnet-affected
        run: dotnet tool install -g dotnet-affected
      - name: Check Affected
        id: check
        run: |
          # Use different comparison based on event
          BASE_REF="${{ github.event_name == 'pull_request' && 'origin/main' || 'HEAD~1' }}"
          dotnet affected --from $BASE_REF --to HEAD
          
          if [ -f affected.proj ]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi
      - name: Upload Affected Project
        if: steps.check.outputs.has_changes == 'true'
        uses: actions/upload-artifact@v6
        with:
          name: affected-project
          path: affected.proj

  test:
    needs: analyze
    if: needs.analyze.outputs.has_changes == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v5
      - uses: actions/download-artifact@v4
        with:
          name: affected-project
      - name: Run Tests
        run: dotnet test affected.proj --configuration Release

  create_nuget:
    needs: analyze
    if: needs.analyze.outputs.has_changes == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v5
      - uses: actions/download-artifact@v7
        with:
          name: affected-project
      - name: Pack
        run: dotnet pack affected.proj --configuration Release --output ./nupkgs
      - name: Upload NuPkgs
        uses: actions/upload-artifact@v6
        with:
          name: nuget-packages
          path: ./nupkgs/*.nupkg

  deploy_preview:
      needs: [test, create_nuget]
      if: github.event_name == 'pull_request'
      runs-on: ubuntu-latest
      steps:
        - uses: actions/download-artifact@v7
          with:
            name: nuget-packages
            path: ./nupkgs
        - name: Push to GitHub Packages
          run: |
            dotnet nuget push "./nupkgs/*.nupkg" \
              --api-key ${{ secrets.GITHUB_TOKEN }} \
              --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json \
              --skip-duplicate

  create_release:
    needs: [test, create_nuget]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install NBGV
        run: dotnet tool install -g nbgv
      - name: Get Version Tag
        id: versioning
        run: |
          VERSION=$(nbgv get-version -v SemVer2)
          echo "tag=v$VERSION" >> $GITHUB_OUTPUT
      - name: Create Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "Release ${{ steps.versioning.outputs.tag }}"
          tag: ${{ steps.versioning.outputs.tag }}
          prerelease: false

  deploy:
    needs: create_release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v7
        with:
          name: nuget-packages
          path: ./nupkgs
      - name: Push to GitHub Packages
        run: |
          dotnet nuget push "./nupkgs/*.nupkg" \
            --api-key ${{ secrets.GITHUB_TOKEN }} \
            --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json \
            #--api-key ${{ secrets.NUGET_API_KEY }} \
            #--source https://api.nuget.org/v3/index.json \
            --skip-duplicate